### ISSUE TITLE
docker-composeにJenkins追加

### ISSUE THREAD

**Issue by hmdknt** [Developper-SE-Garden/tms#11]
### Description
概要レベルの内容を記載する。
docker-composeにjenkins追加する。travis-ciを使う予定であったが、 jenkinsの復習も踏まえて
jenkinsを使わせていただきたい。
----

### Details
詳細な内容を記載する。  
まずは、Descriptionを埋めて後ほどDetailsを記載するのもOKとする。

----
### Relation Issue
関連Issueがあるのであれば記載する。

- ＃番号を記載することでリンクとなる
----

**Comment by takashno** [comment]
Jenkinsでも構いませんが、開発環境用とは別だと思いますので
それとは別としてもらいたいです。

**Comment by alp-takashno** [comment]
あと、できればOpenLDAPをお願いしたいです。
今回はActiveDirectoryを対象としますが、開発はLDAPでもいいと思いますので。
まだ調査をきちんとしていませんが、悪しからず。。。
