### ISSUE TITLE
docker-composeでmysqlの立ち上げが出来ない

### ISSUE THREAD

**Issue by hmdknt** [Developper-SE-Garden/tms#24]
### Description

docker-compose runでmysqlの立ち上げだけが出来なくなってしまった。

----

### Details
psでstatusを見るとExit 128が表示されている。

 エラーの内容は以下のようになっている
ERROR: for develop_database_1  Cannot start service database: driver failed programming external connectivity on endpoint develop_database_1 (adf1692c5af9d6c2ffbf75b1e7f89b053dd28c06bc1ed8ef7d78691d68c4cf7d): Error starting userland proxy: Bind for 0.0.0.0:3306 failed: port is already allocated

問題記録用のissue。これからerrorを直す。

----

### Relation Issue
関連Issueがあるのであれば記載する。

- ＃番号を記載することでリンクとなる
----

**Comment by alp-takashno** [comment]
基本的には、docker-compose rm で一度消してみるしかない。
→ダメだったと言っていた。

**Comment by hmdknt** [comment]
MySQLをインストールした時にMySQLサーバーが立ってしまったのが原因であった
