### ISSUE TITLE
タスク整理、進め方

### ISSUE THREAD

**Issue by btkigamim** [Developper-SE-Garden/tms#37]
### Description
開発が停滞してしまっているので、タスク化して他の方も作業に取り掛かれるようにしたい。

以下の画面設計単位で設計からテストまでタスクを分けてできる人から進めていく方針でどうでしょうか。
* ログイン
* インデックス（Top画面）
* マイページ（GitHubみたいなイメージ）、ヘルプ画面
* レポート一覧
* レポート作成
* レポート編集（作成画面と一部流用）
* レポート検索
* 運用インデックス（運用者用Top画面）
* トレーナー設定

----

### Details

★マークはレビュー依頼のタイミング

1. 画面設計
2. 画面遷移図
3. 機能一覧★
4. シーケンス図
5. IF仕様書★
6. ビジネスロジック定義書
7. ER図★

各タスクの詳細は以下のイメージ。

1.画面設計

画面のフォームやボタンなどの配置をイメージ図に起こす。
　→機能を抽出する。

2.画面遷移図

実現する機能に複数画面が必要な場合（確認、完了画面など）画面遷移図を書く。

3.機能一覧

画面設計の中で抽出した機能を一覧化する。

4.シーケンス図

画面からサーバへの処理の流れをシーケンス図に起こす。

5.IF仕様書

シーケンス図の中でやり取りする情報をまとめる。

6.ビジネスロジック定義書

サーバ側で行うロジックを定義する。

7.ER図

DBとどういった情報のやり取りをするかを定義する。

**Comment by btishinoyu** [comment]
以下も定めておきたい。
* 画像作成で使用するツール
* 書く場所（章）

1.画面設計
* [PlantUML ワイヤーフレーム](http://plantuml.com/salt)
* 基本設計 - 画面設計 - 機能名

2.画面遷移図
* [PlantUML Ditaa](http://plantuml.com/ditaa)
* 基本設計 - 画面遷移図 - 機能名

3.機能一覧★
* － (特になし)
* 基本設計 - 機能一覧  を補記／修正

4.シーケンス図
* [PlantUML シーケンス図](http://plantuml.com/sequence-diagram)
* 基本設計 - 機能設計書 - 機能名

5.IF仕様書★
* swagger
* 詳細設計 - オンライン処理設計書 - （うーん…swaggerで出力したドキュメントのパス貼る？）

6.ビジネスロジック定義書
* － (特になし)
* 詳細設計 - オンライン処理設計書 - 機能名 - 処理概要

7.ER図★
* MySQL Workbench 
* モデリング - ER図 （どう載せる？mwbまだよくわからん。）
